#! /bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $APP_USERNAME WITH PASSWORD '$APP_PASSWORD';
    CREATE ROLE external_connection;
    GRANT external_connection TO $APP_USERNAME;
    CREATE DATABASE $POSTGRES_DB;
    ALTER USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
EOSQL