/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/calculator/scene.gltf -t -r public 
Author: Powerbyte7 (https://sketchfab.com/Powerbyte7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/calculator-d9ffbc4bbe1044bb902e1dddac52b0de
Title: Calculator
*/
'use client';

import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
}



type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Calculator(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/calculator/scene.gltf') as GLTFResult
  
  const [theta, setTheta] = useState<number>(0);
  const [xRot, setXRot] = useState<number>(1.5);
  const [zRot, setZRot] = useState<number>(0);


  const ref = useRef<any>(null);


  useFrame(() => { 
    if (ref.current) {
      setTheta(theta => theta + 0.01);

      if (ref.current.position) {
          const x = 5 * Math.cos(theta);
          const z = 5 * Math.sin(theta);
          ref.current.position.set(x, 0, z);
      }
          
      if (ref.current.rotation) {
        setZRot(zRot => zRot + 0.03);
        setXRot(xRot => xRot + 0.005);
        ref.current.rotation.set(xRot, 0, zRot)
      }      
    } else {
      return;
    }
  }); 
  
  return (
    <group ref={ref} {...props} dispose={null} rotation={[1.5, 0, 0]}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/calculator/scene.gltf')
