/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/eraser/scene.gltf -t -r public 
Author: Artieee (https://sketchfab.com/Artieee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/some-eraser-two-0bdd6e5a1a0845759357b5564e588f5c
Title: Some eraser two
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Eraser_Low_eraser1_0: THREE.Mesh
  }
  materials: {
    eraser1: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Eraser(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/eraser/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.5}>
      <group>
        <mesh geometry={nodes.Eraser_Low_eraser1_0.geometry} material={materials.eraser1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/eraser/scene.gltf')
