/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/monitor/scene.gltf -t -r public 
Author: portgl16 (https://sketchfab.com/portgl16)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monitor-9f6f9018f14a4dbea1ad1aea0ce89e7c
Title: Monitor
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_Case_0: THREE.Mesh
    Cube_RenderMonitor_0: THREE.Mesh
    Cube_USB_0: THREE.Mesh
    Button_Button_Material_0: THREE.Mesh
    Button_two_ButtonTwoMaterial_0: THREE.Mesh
    Button_two001_ButtonTwoMaterial001_0: THREE.Mesh
  }
  materials: {
    Case: THREE.MeshStandardMaterial
    RenderMonitor: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Button_Material: THREE.MeshStandardMaterial
    ButtonTwoMaterial: THREE.MeshStandardMaterial
    ['ButtonTwoMaterial.001']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Monitor(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/monitor/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.3}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube_Case_0.geometry} material={materials.Case} />
        <mesh geometry={nodes.Cube_RenderMonitor_0.geometry} material={materials.RenderMonitor} />
        <mesh geometry={nodes.Cube_USB_0.geometry} material={materials.material} />
      </group>
      <mesh geometry={nodes.Button_Button_Material_0.geometry} material={materials.Button_Material} position={[-695.83, -497.371, 28.549]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Button_two_ButtonTwoMaterial_0.geometry} material={materials.ButtonTwoMaterial} position={[-740.479, -496.832, 27.902]} rotation={[-Math.PI / 2, 0, 0]} scale={[20, 10, 8]} />
      <mesh geometry={nodes.Button_two001_ButtonTwoMaterial001_0.geometry} material={materials['ButtonTwoMaterial.001']} position={[-792.221, -496.832, 27.902]} rotation={[-Math.PI / 2, 0, 0]} scale={[20, 10, 8]} />
    </group>
  )
}

useGLTF.preload('/models/monitor/scene.gltf')
