/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/notebook/scene.gltf -t -r public 
Author: Alain Sorazu (https://sketchfab.com/alainsorazu)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/notebook-b0ee64ec4a504764ab07eb93a1076feb
Title: Notebook
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
  }
  materials: {
    Sheets: THREE.MeshStandardMaterial
    Cover: THREE.MeshStandardMaterial
    Binding: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Notebook(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/notebook/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} rotation={[1, 0, 0]}>
      <group>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Sheets} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Sheets} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Cover} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Binding} />
      </group>
    </group>
  )
}

useGLTF.preload('/notebook/scene.gltf')
